- name: demo on inventory variables
  hosts: frontend
  #connection: local
  tasks:
  - name: demo on inventory variables
  debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"